---
- name: update all packes on system
  hosts: all
  vars:
    administrator_name: corpadmin
    administrator_password: $6$mysecretsalt$qJbapG68nyRab3gxvKWPUcs2g3t0oMHSHMnSKecYNpSi3CuZm.GbBqXO8BE6EI6P1JUefhA0qvD7b5LSh./PU1
    become: yes
  tasks: 
  - name: update all software packages
    yum:
        name: '*'
        state: latest
    become: yes
- name: install nginx on web1 and copy files
  hosts: web1
  tasks:
  - name: install nginx
    yum: 
        name: nginx
        state: latest
    become: yes
  - name: copy j2 file to the system directory
    template:
        src: default.conf.j2
        dest: /etc/nginx/conf.d/default.conf
    become: yes
  - name: start nginx and enable after boot
    service:
        name: nginx
        state: started
        enabled: yes
    become: yes
- name: install mysql server package and configure in a way that it is running after reboot and also create 5 directories using loop
  hosts: database1
  tasks:
  - name: install mysql server package
    yum:
        name: mysql-server
        state: installed
    become: yes
  - name: run after reboot
    service:
        name: mysqld
        state: started
        enabled: yes
    become: yes
  - name: create 5 loop directories
    file: 
        dest: /var/data/client{{item}}
        state: directory
    with_sequence: start=1 end=5
    become: yes
